### ISSUE TITLE
Panic: `Cannot connect to GitHub API`: `Address family not supported by protocol family` 💥

### ISSUE THREAD

**Issue by nicokosi** [nicokosi/pullpito#116]
```
$ RUST_BACKTRACE=1 cargo run -- --repository nicokosi/pullpito
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/pullpito --repository nicokosi/pullpito`
thread '<unnamed>' panicked at 'Cannot connect to GitHub API: Error(Hyper(Error(Connect, Os { code: 47, kind: Uncategorized, message: "Address family not supported by protocol family" })), "https://api.github.com/repos/nicokosi/pullpito/events?page=1")', src/github_events/mod.rs:27:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1064:23
   4: pullpito::github_events::github_events
             at ./src/github_events/mod.rs:23:24
   5: pullpito::log_github_events::{{closure}}
             at ./src/lib.rs:83:58
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Additional information (not sure if useful 🤷):
```
$ cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)

$ sw_vers
ProductName:	macOS
ProductVersion:	11.7.1
BuildVersion:	20G918
```

**Comment by nicokosi** [comment]
Note that panic does not occur with installed binary:
```
$ cargo install --path .
  Installing pullpito v0.1.1 (/Users/nicolas/work/pullpito)
    Updating crates.io index
    Finished release [optimized] target(s) in 0.37s
   Replacing /Users/nicolas/.cargo/bin/pullpito
    Replaced package `pullpito v0.1.1 (/Users/nicolas/work/pullpito)` with `pullpito v0.1.1 (/Users/nicolas/work/pullpito)` (executable `pullpito`)

$ target/release/pullpito --repository nicokosi/pullpito
pull requests for "nicokosi/pullpito" ->
  opened per author:
    nicokosi: 2
    dependabot[bot]: 3
  commented per author:
    dependabot[bot]: 3
  closed per author:
    nicokosi: 1
    dependabot[bot]: 3
```

**Comment by nicokosi** [comment]
I really should upgrade `reqwest`to latest... see https://github.com/nicokosi/pullpito/pull/101 🙄

**Comment by nicokosi** [comment]
> Not sure if related but I really should upgrade `reqwest`to latest... see #101 🙄

See https://github.com/nicokosi/pullpito/pull/120.

**Comment by nicokosi** [comment]
Fixed by https://github.com/nicokosi/pullpito/pull/131. ✌️
