### ISSUE TITLE
'pullpito nicokosi/hubstats' panics

### ISSUE THREAD

**Issue by nicokosi** [nicokosi/pullpito#19]
`pullpito nicokosi/hubstats` fails:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
```

**Comment by nicokosi** [comment]
Full stack trace:
```
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: pullpito::github_events::github_events
             at src/github_events/mod.rs:59
  11: pullpito::github_events::{{closure}}
             at src/lib.rs:64
```

**Comment by nicokosi** [comment]
Cannot reproduce today:
```
pullpito nicokosi/hubstats
pull requests for "nicokosi/hubstats" ->
  opened per author:
    nicokosi: 1
  commented per author:
    nicokosi: 2
  closed per author:
```
Issue may be related to GitHub rate limit.
Anyway, fixing issue #10 would help!

**Comment by nicokosi** [comment]
GitHub 'events' API returns no 'Link' HTTP header with pagination info if only one page is returned.
For instance, `http --headers "https://api.github.com/repos/nicokosi/hubstats/events"` shows:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: public, max-age=60, s-maxage=60
Content-Encoding: gzip
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 22 Jul 2018 17:09:23 GMT
ETag: W/"341d111422247e97fded748ffdd78538"
Last-Modified: Fri, 11 May 2018 07:03:43 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Transfer-Encoding: chunked
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-GitHub-Media-Type: github.v3; format=json
X-GitHub-Request-Id: C659:4372:148C1EE:2A69DCE:5B54BA43
X-Poll-Interval: 60
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 46
X-RateLimit-Reset: 1532282663
X-Runtime-rack: 0.045368
X-XSS-Protection: 1; mode=block
```
